/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as TransportationBookingsRouteImport } from './routes/transportation-bookings'
import { Route as ServiceOrdersRouteImport } from './routes/service-orders'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as MasterTransportRouteImport } from './routes/master-transport'
import { Route as MasterHotelsRouteImport } from './routes/master-hotels'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InvoiceDetailRouteImport } from './routes/invoice-detail'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateTransportationBookingRouteImport } from './routes/create-transportation-booking'
import { Route as CreateServiceOrderRouteImport } from './routes/create-service-order'
import { Route as CreateReceiptRouteImport } from './routes/create-receipt'
import { Route as CreateMasterTransportRouteImport } from './routes/create-master-transport'
import { Route as CreateMasterHotelRouteImport } from './routes/create-master-hotel'
import { Route as CreateInvoiceRouteImport } from './routes/create-invoice'
import { Route as CreateBookingRouteImport } from './routes/create-booking'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ClearAuthCacheRouteImport } from './routes/clear-auth-cache'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookingEditRouteImport } from './routes/booking-edit'
import { Route as BookingDetailRouteImport } from './routes/booking-detail'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as VouchersCreateRouteImport } from './routes/vouchers/create'
import { Route as TransportationBookingEditTransportationBookingIdRouteImport } from './routes/transportation-booking-edit.$transportationBookingId'
import { Route as TransportationBookingDetailTransportationBookingIdRouteImport } from './routes/transportation-booking-detail.$transportationBookingId'
import { Route as ServiceOrdersCreateRouteImport } from './routes/service-orders/create'
import { Route as ServiceOrdersIdRouteImport } from './routes/service-orders/$id'
import { Route as ServiceOrderEditServiceOrderIdRouteImport } from './routes/service-order-edit.$serviceOrderId'
import { Route as ServiceOrderDetailServiceOrderIdRouteImport } from './routes/service-order-detail.$serviceOrderId'
import { Route as MasterTransportEditRouteIdRouteImport } from './routes/master-transport-edit.$routeId'
import { Route as MasterTransportDetailRouteIdRouteImport } from './routes/master-transport-detail.$routeId'
import { Route as MasterHotelEditHotelIdRouteImport } from './routes/master-hotel-edit.$hotelId'
import { Route as MasterHotelDetailHotelIdRouteImport } from './routes/master-hotel-detail.$hotelId'
import { Route as DashboardUserRouteImport } from './routes/dashboard/user'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as CreateTransportPricingRouteIdRouteImport } from './routes/create-transport-pricing.$routeId'
import { Route as CreateHotelPricingHotelIdRouteImport } from './routes/create-hotel-pricing.$hotelId'
import { Route as ClientsCreateRouteImport } from './routes/clients/create'
import { Route as ClientDetailClientIdRouteImport } from './routes/client-detail.$clientId'
import { Route as BookingViewBookingIdRouteImport } from './routes/booking-view.$bookingId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as EditTransportPricingRouteIdPricingIdRouteImport } from './routes/edit-transport-pricing.$routeId.$pricingId'
import { Route as EditHotelPricingHotelIdPricingIdRouteImport } from './routes/edit-hotel-pricing.$hotelId.$pricingId'
import { Route as BookingsBookingIdEditRouteImport } from './routes/bookings/$bookingId/edit'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportationBookingsRoute = TransportationBookingsRouteImport.update({
  id: '/transportation-bookings',
  path: '/transportation-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceOrdersRoute = ServiceOrdersRouteImport.update({
  id: '/service-orders',
  path: '/service-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterTransportRoute = MasterTransportRouteImport.update({
  id: '/master-transport',
  path: '/master-transport',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterHotelsRoute = MasterHotelsRouteImport.update({
  id: '/master-hotels',
  path: '/master-hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceDetailRoute = InvoiceDetailRouteImport.update({
  id: '/invoice-detail',
  path: '/invoice-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTransportationBookingRoute =
  CreateTransportationBookingRouteImport.update({
    id: '/create-transportation-booking',
    path: '/create-transportation-booking',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreateServiceOrderRoute = CreateServiceOrderRouteImport.update({
  id: '/create-service-order',
  path: '/create-service-order',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReceiptRoute = CreateReceiptRouteImport.update({
  id: '/create-receipt',
  path: '/create-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMasterTransportRoute = CreateMasterTransportRouteImport.update({
  id: '/create-master-transport',
  path: '/create-master-transport',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMasterHotelRoute = CreateMasterHotelRouteImport.update({
  id: '/create-master-hotel',
  path: '/create-master-hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateInvoiceRoute = CreateInvoiceRouteImport.update({
  id: '/create-invoice',
  path: '/create-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBookingRoute = CreateBookingRouteImport.update({
  id: '/create-booking',
  path: '/create-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearAuthCacheRoute = ClearAuthCacheRouteImport.update({
  id: '/clear-auth-cache',
  path: '/clear-auth-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingEditRoute = BookingEditRouteImport.update({
  id: '/booking-edit',
  path: '/booking-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingDetailRoute = BookingDetailRouteImport.update({
  id: '/booking-detail',
  path: '/booking-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const VouchersCreateRoute = VouchersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => VouchersRoute,
} as any)
const TransportationBookingEditTransportationBookingIdRoute =
  TransportationBookingEditTransportationBookingIdRouteImport.update({
    id: '/transportation-booking-edit/$transportationBookingId',
    path: '/transportation-booking-edit/$transportationBookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransportationBookingDetailTransportationBookingIdRoute =
  TransportationBookingDetailTransportationBookingIdRouteImport.update({
    id: '/transportation-booking-detail/$transportationBookingId',
    path: '/transportation-booking-detail/$transportationBookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceOrdersCreateRoute = ServiceOrdersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ServiceOrdersRoute,
} as any)
const ServiceOrdersIdRoute = ServiceOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ServiceOrdersRoute,
} as any)
const ServiceOrderEditServiceOrderIdRoute =
  ServiceOrderEditServiceOrderIdRouteImport.update({
    id: '/service-order-edit/$serviceOrderId',
    path: '/service-order-edit/$serviceOrderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceOrderDetailServiceOrderIdRoute =
  ServiceOrderDetailServiceOrderIdRouteImport.update({
    id: '/service-order-detail/$serviceOrderId',
    path: '/service-order-detail/$serviceOrderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterTransportEditRouteIdRoute =
  MasterTransportEditRouteIdRouteImport.update({
    id: '/master-transport-edit/$routeId',
    path: '/master-transport-edit/$routeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterTransportDetailRouteIdRoute =
  MasterTransportDetailRouteIdRouteImport.update({
    id: '/master-transport-detail/$routeId',
    path: '/master-transport-detail/$routeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterHotelEditHotelIdRoute = MasterHotelEditHotelIdRouteImport.update({
  id: '/master-hotel-edit/$hotelId',
  path: '/master-hotel-edit/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterHotelDetailHotelIdRoute =
  MasterHotelDetailHotelIdRouteImport.update({
    id: '/master-hotel-detail/$hotelId',
    path: '/master-hotel-detail/$hotelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const CreateTransportPricingRouteIdRoute =
  CreateTransportPricingRouteIdRouteImport.update({
    id: '/create-transport-pricing/$routeId',
    path: '/create-transport-pricing/$routeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreateHotelPricingHotelIdRoute =
  CreateHotelPricingHotelIdRouteImport.update({
    id: '/create-hotel-pricing/$hotelId',
    path: '/create-hotel-pricing/$hotelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientsCreateRoute = ClientsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientDetailClientIdRoute = ClientDetailClientIdRouteImport.update({
  id: '/client-detail/$clientId',
  path: '/client-detail/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingViewBookingIdRoute = BookingViewBookingIdRouteImport.update({
  id: '/booking-view/$bookingId',
  path: '/booking-view/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const EditTransportPricingRouteIdPricingIdRoute =
  EditTransportPricingRouteIdPricingIdRouteImport.update({
    id: '/edit-transport-pricing/$routeId/$pricingId',
    path: '/edit-transport-pricing/$routeId/$pricingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EditHotelPricingHotelIdPricingIdRoute =
  EditHotelPricingHotelIdPricingIdRouteImport.update({
    id: '/edit-hotel-pricing/$hotelId/$pricingId',
    path: '/edit-hotel-pricing/$hotelId/$pricingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingsBookingIdEditRoute = BookingsBookingIdEditRouteImport.update({
  id: '/$bookingId/edit',
  path: '/$bookingId/edit',
  getParentRoute: () => BookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/booking-detail': typeof BookingDetailRoute
  '/booking-edit': typeof BookingEditRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/clear-auth-cache': typeof ClearAuthCacheRoute
  '/clients': typeof ClientsRouteWithChildren
  '/costs': typeof CostsRoute
  '/create-booking': typeof CreateBookingRoute
  '/create-invoice': typeof CreateInvoiceRoute
  '/create-master-hotel': typeof CreateMasterHotelRoute
  '/create-master-transport': typeof CreateMasterTransportRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/create-service-order': typeof CreateServiceOrderRoute
  '/create-transportation-booking': typeof CreateTransportationBookingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoice-detail': typeof InvoiceDetailRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/master-hotels': typeof MasterHotelsRoute
  '/master-transport': typeof MasterTransportRoute
  '/receipts': typeof ReceiptsRoute
  '/register': typeof RegisterRoute
  '/service-orders': typeof ServiceOrdersRouteWithChildren
  '/transportation-bookings': typeof TransportationBookingsRoute
  '/vouchers': typeof VouchersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/booking-view/$bookingId': typeof BookingViewBookingIdRoute
  '/client-detail/$clientId': typeof ClientDetailClientIdRoute
  '/clients/create': typeof ClientsCreateRoute
  '/create-hotel-pricing/$hotelId': typeof CreateHotelPricingHotelIdRoute
  '/create-transport-pricing/$routeId': typeof CreateTransportPricingRouteIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/master-hotel-detail/$hotelId': typeof MasterHotelDetailHotelIdRoute
  '/master-hotel-edit/$hotelId': typeof MasterHotelEditHotelIdRoute
  '/master-transport-detail/$routeId': typeof MasterTransportDetailRouteIdRoute
  '/master-transport-edit/$routeId': typeof MasterTransportEditRouteIdRoute
  '/service-order-detail/$serviceOrderId': typeof ServiceOrderDetailServiceOrderIdRoute
  '/service-order-edit/$serviceOrderId': typeof ServiceOrderEditServiceOrderIdRoute
  '/service-orders/$id': typeof ServiceOrdersIdRoute
  '/service-orders/create': typeof ServiceOrdersCreateRoute
  '/transportation-booking-detail/$transportationBookingId': typeof TransportationBookingDetailTransportationBookingIdRoute
  '/transportation-booking-edit/$transportationBookingId': typeof TransportationBookingEditTransportationBookingIdRoute
  '/vouchers/create': typeof VouchersCreateRoute
  '/clients/': typeof ClientsIndexRoute
  '/bookings/$bookingId/edit': typeof BookingsBookingIdEditRoute
  '/edit-hotel-pricing/$hotelId/$pricingId': typeof EditHotelPricingHotelIdPricingIdRoute
  '/edit-transport-pricing/$routeId/$pricingId': typeof EditTransportPricingRouteIdPricingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/booking-detail': typeof BookingDetailRoute
  '/booking-edit': typeof BookingEditRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/clear-auth-cache': typeof ClearAuthCacheRoute
  '/costs': typeof CostsRoute
  '/create-booking': typeof CreateBookingRoute
  '/create-invoice': typeof CreateInvoiceRoute
  '/create-master-hotel': typeof CreateMasterHotelRoute
  '/create-master-transport': typeof CreateMasterTransportRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/create-service-order': typeof CreateServiceOrderRoute
  '/create-transportation-booking': typeof CreateTransportationBookingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoice-detail': typeof InvoiceDetailRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/master-hotels': typeof MasterHotelsRoute
  '/master-transport': typeof MasterTransportRoute
  '/receipts': typeof ReceiptsRoute
  '/register': typeof RegisterRoute
  '/service-orders': typeof ServiceOrdersRouteWithChildren
  '/transportation-bookings': typeof TransportationBookingsRoute
  '/vouchers': typeof VouchersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/booking-view/$bookingId': typeof BookingViewBookingIdRoute
  '/client-detail/$clientId': typeof ClientDetailClientIdRoute
  '/clients/create': typeof ClientsCreateRoute
  '/create-hotel-pricing/$hotelId': typeof CreateHotelPricingHotelIdRoute
  '/create-transport-pricing/$routeId': typeof CreateTransportPricingRouteIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/master-hotel-detail/$hotelId': typeof MasterHotelDetailHotelIdRoute
  '/master-hotel-edit/$hotelId': typeof MasterHotelEditHotelIdRoute
  '/master-transport-detail/$routeId': typeof MasterTransportDetailRouteIdRoute
  '/master-transport-edit/$routeId': typeof MasterTransportEditRouteIdRoute
  '/service-order-detail/$serviceOrderId': typeof ServiceOrderDetailServiceOrderIdRoute
  '/service-order-edit/$serviceOrderId': typeof ServiceOrderEditServiceOrderIdRoute
  '/service-orders/$id': typeof ServiceOrdersIdRoute
  '/service-orders/create': typeof ServiceOrdersCreateRoute
  '/transportation-booking-detail/$transportationBookingId': typeof TransportationBookingDetailTransportationBookingIdRoute
  '/transportation-booking-edit/$transportationBookingId': typeof TransportationBookingEditTransportationBookingIdRoute
  '/vouchers/create': typeof VouchersCreateRoute
  '/clients': typeof ClientsIndexRoute
  '/bookings/$bookingId/edit': typeof BookingsBookingIdEditRoute
  '/edit-hotel-pricing/$hotelId/$pricingId': typeof EditHotelPricingHotelIdPricingIdRoute
  '/edit-transport-pricing/$routeId/$pricingId': typeof EditTransportPricingRouteIdPricingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/booking-detail': typeof BookingDetailRoute
  '/booking-edit': typeof BookingEditRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/clear-auth-cache': typeof ClearAuthCacheRoute
  '/clients': typeof ClientsRouteWithChildren
  '/costs': typeof CostsRoute
  '/create-booking': typeof CreateBookingRoute
  '/create-invoice': typeof CreateInvoiceRoute
  '/create-master-hotel': typeof CreateMasterHotelRoute
  '/create-master-transport': typeof CreateMasterTransportRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/create-service-order': typeof CreateServiceOrderRoute
  '/create-transportation-booking': typeof CreateTransportationBookingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoice-detail': typeof InvoiceDetailRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/master-hotels': typeof MasterHotelsRoute
  '/master-transport': typeof MasterTransportRoute
  '/receipts': typeof ReceiptsRoute
  '/register': typeof RegisterRoute
  '/service-orders': typeof ServiceOrdersRouteWithChildren
  '/transportation-bookings': typeof TransportationBookingsRoute
  '/vouchers': typeof VouchersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/booking-view/$bookingId': typeof BookingViewBookingIdRoute
  '/client-detail/$clientId': typeof ClientDetailClientIdRoute
  '/clients/create': typeof ClientsCreateRoute
  '/create-hotel-pricing/$hotelId': typeof CreateHotelPricingHotelIdRoute
  '/create-transport-pricing/$routeId': typeof CreateTransportPricingRouteIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/master-hotel-detail/$hotelId': typeof MasterHotelDetailHotelIdRoute
  '/master-hotel-edit/$hotelId': typeof MasterHotelEditHotelIdRoute
  '/master-transport-detail/$routeId': typeof MasterTransportDetailRouteIdRoute
  '/master-transport-edit/$routeId': typeof MasterTransportEditRouteIdRoute
  '/service-order-detail/$serviceOrderId': typeof ServiceOrderDetailServiceOrderIdRoute
  '/service-order-edit/$serviceOrderId': typeof ServiceOrderEditServiceOrderIdRoute
  '/service-orders/$id': typeof ServiceOrdersIdRoute
  '/service-orders/create': typeof ServiceOrdersCreateRoute
  '/transportation-booking-detail/$transportationBookingId': typeof TransportationBookingDetailTransportationBookingIdRoute
  '/transportation-booking-edit/$transportationBookingId': typeof TransportationBookingEditTransportationBookingIdRoute
  '/vouchers/create': typeof VouchersCreateRoute
  '/clients/': typeof ClientsIndexRoute
  '/bookings/$bookingId/edit': typeof BookingsBookingIdEditRoute
  '/edit-hotel-pricing/$hotelId/$pricingId': typeof EditHotelPricingHotelIdPricingIdRoute
  '/edit-transport-pricing/$routeId/$pricingId': typeof EditTransportPricingRouteIdPricingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/booking-detail'
    | '/booking-edit'
    | '/bookings'
    | '/clear-auth-cache'
    | '/clients'
    | '/costs'
    | '/create-booking'
    | '/create-invoice'
    | '/create-master-hotel'
    | '/create-master-transport'
    | '/create-receipt'
    | '/create-service-order'
    | '/create-transportation-booking'
    | '/dashboard'
    | '/forgot-password'
    | '/invoice-detail'
    | '/invoices'
    | '/login'
    | '/master-hotels'
    | '/master-transport'
    | '/receipts'
    | '/register'
    | '/service-orders'
    | '/transportation-bookings'
    | '/vouchers'
    | '/auth/callback'
    | '/booking-view/$bookingId'
    | '/client-detail/$clientId'
    | '/clients/create'
    | '/create-hotel-pricing/$hotelId'
    | '/create-transport-pricing/$routeId'
    | '/dashboard/admin'
    | '/dashboard/user'
    | '/master-hotel-detail/$hotelId'
    | '/master-hotel-edit/$hotelId'
    | '/master-transport-detail/$routeId'
    | '/master-transport-edit/$routeId'
    | '/service-order-detail/$serviceOrderId'
    | '/service-order-edit/$serviceOrderId'
    | '/service-orders/$id'
    | '/service-orders/create'
    | '/transportation-booking-detail/$transportationBookingId'
    | '/transportation-booking-edit/$transportationBookingId'
    | '/vouchers/create'
    | '/clients/'
    | '/bookings/$bookingId/edit'
    | '/edit-hotel-pricing/$hotelId/$pricingId'
    | '/edit-transport-pricing/$routeId/$pricingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/booking-detail'
    | '/booking-edit'
    | '/bookings'
    | '/clear-auth-cache'
    | '/costs'
    | '/create-booking'
    | '/create-invoice'
    | '/create-master-hotel'
    | '/create-master-transport'
    | '/create-receipt'
    | '/create-service-order'
    | '/create-transportation-booking'
    | '/dashboard'
    | '/forgot-password'
    | '/invoice-detail'
    | '/invoices'
    | '/login'
    | '/master-hotels'
    | '/master-transport'
    | '/receipts'
    | '/register'
    | '/service-orders'
    | '/transportation-bookings'
    | '/vouchers'
    | '/auth/callback'
    | '/booking-view/$bookingId'
    | '/client-detail/$clientId'
    | '/clients/create'
    | '/create-hotel-pricing/$hotelId'
    | '/create-transport-pricing/$routeId'
    | '/dashboard/admin'
    | '/dashboard/user'
    | '/master-hotel-detail/$hotelId'
    | '/master-hotel-edit/$hotelId'
    | '/master-transport-detail/$routeId'
    | '/master-transport-edit/$routeId'
    | '/service-order-detail/$serviceOrderId'
    | '/service-order-edit/$serviceOrderId'
    | '/service-orders/$id'
    | '/service-orders/create'
    | '/transportation-booking-detail/$transportationBookingId'
    | '/transportation-booking-edit/$transportationBookingId'
    | '/vouchers/create'
    | '/clients'
    | '/bookings/$bookingId/edit'
    | '/edit-hotel-pricing/$hotelId/$pricingId'
    | '/edit-transport-pricing/$routeId/$pricingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/booking-detail'
    | '/booking-edit'
    | '/bookings'
    | '/clear-auth-cache'
    | '/clients'
    | '/costs'
    | '/create-booking'
    | '/create-invoice'
    | '/create-master-hotel'
    | '/create-master-transport'
    | '/create-receipt'
    | '/create-service-order'
    | '/create-transportation-booking'
    | '/dashboard'
    | '/forgot-password'
    | '/invoice-detail'
    | '/invoices'
    | '/login'
    | '/master-hotels'
    | '/master-transport'
    | '/receipts'
    | '/register'
    | '/service-orders'
    | '/transportation-bookings'
    | '/vouchers'
    | '/auth/callback'
    | '/booking-view/$bookingId'
    | '/client-detail/$clientId'
    | '/clients/create'
    | '/create-hotel-pricing/$hotelId'
    | '/create-transport-pricing/$routeId'
    | '/dashboard/admin'
    | '/dashboard/user'
    | '/master-hotel-detail/$hotelId'
    | '/master-hotel-edit/$hotelId'
    | '/master-transport-detail/$routeId'
    | '/master-transport-edit/$routeId'
    | '/service-order-detail/$serviceOrderId'
    | '/service-order-edit/$serviceOrderId'
    | '/service-orders/$id'
    | '/service-orders/create'
    | '/transportation-booking-detail/$transportationBookingId'
    | '/transportation-booking-edit/$transportationBookingId'
    | '/vouchers/create'
    | '/clients/'
    | '/bookings/$bookingId/edit'
    | '/edit-hotel-pricing/$hotelId/$pricingId'
    | '/edit-transport-pricing/$routeId/$pricingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookingDetailRoute: typeof BookingDetailRoute
  BookingEditRoute: typeof BookingEditRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  ClearAuthCacheRoute: typeof ClearAuthCacheRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  CostsRoute: typeof CostsRoute
  CreateBookingRoute: typeof CreateBookingRoute
  CreateInvoiceRoute: typeof CreateInvoiceRoute
  CreateMasterHotelRoute: typeof CreateMasterHotelRoute
  CreateMasterTransportRoute: typeof CreateMasterTransportRoute
  CreateReceiptRoute: typeof CreateReceiptRoute
  CreateServiceOrderRoute: typeof CreateServiceOrderRoute
  CreateTransportationBookingRoute: typeof CreateTransportationBookingRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvoiceDetailRoute: typeof InvoiceDetailRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  MasterHotelsRoute: typeof MasterHotelsRoute
  MasterTransportRoute: typeof MasterTransportRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RegisterRoute: typeof RegisterRoute
  ServiceOrdersRoute: typeof ServiceOrdersRouteWithChildren
  TransportationBookingsRoute: typeof TransportationBookingsRoute
  VouchersRoute: typeof VouchersRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  BookingViewBookingIdRoute: typeof BookingViewBookingIdRoute
  ClientDetailClientIdRoute: typeof ClientDetailClientIdRoute
  CreateHotelPricingHotelIdRoute: typeof CreateHotelPricingHotelIdRoute
  CreateTransportPricingRouteIdRoute: typeof CreateTransportPricingRouteIdRoute
  MasterHotelDetailHotelIdRoute: typeof MasterHotelDetailHotelIdRoute
  MasterHotelEditHotelIdRoute: typeof MasterHotelEditHotelIdRoute
  MasterTransportDetailRouteIdRoute: typeof MasterTransportDetailRouteIdRoute
  MasterTransportEditRouteIdRoute: typeof MasterTransportEditRouteIdRoute
  ServiceOrderDetailServiceOrderIdRoute: typeof ServiceOrderDetailServiceOrderIdRoute
  ServiceOrderEditServiceOrderIdRoute: typeof ServiceOrderEditServiceOrderIdRoute
  TransportationBookingDetailTransportationBookingIdRoute: typeof TransportationBookingDetailTransportationBookingIdRoute
  TransportationBookingEditTransportationBookingIdRoute: typeof TransportationBookingEditTransportationBookingIdRoute
  EditHotelPricingHotelIdPricingIdRoute: typeof EditHotelPricingHotelIdPricingIdRoute
  EditTransportPricingRouteIdPricingIdRoute: typeof EditTransportPricingRouteIdPricingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportation-bookings': {
      id: '/transportation-bookings'
      path: '/transportation-bookings'
      fullPath: '/transportation-bookings'
      preLoaderRoute: typeof TransportationBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-orders': {
      id: '/service-orders'
      path: '/service-orders'
      fullPath: '/service-orders'
      preLoaderRoute: typeof ServiceOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-transport': {
      id: '/master-transport'
      path: '/master-transport'
      fullPath: '/master-transport'
      preLoaderRoute: typeof MasterTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-hotels': {
      id: '/master-hotels'
      path: '/master-hotels'
      fullPath: '/master-hotels'
      preLoaderRoute: typeof MasterHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-detail': {
      id: '/invoice-detail'
      path: '/invoice-detail'
      fullPath: '/invoice-detail'
      preLoaderRoute: typeof InvoiceDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-transportation-booking': {
      id: '/create-transportation-booking'
      path: '/create-transportation-booking'
      fullPath: '/create-transportation-booking'
      preLoaderRoute: typeof CreateTransportationBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-service-order': {
      id: '/create-service-order'
      path: '/create-service-order'
      fullPath: '/create-service-order'
      preLoaderRoute: typeof CreateServiceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-receipt': {
      id: '/create-receipt'
      path: '/create-receipt'
      fullPath: '/create-receipt'
      preLoaderRoute: typeof CreateReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-master-transport': {
      id: '/create-master-transport'
      path: '/create-master-transport'
      fullPath: '/create-master-transport'
      preLoaderRoute: typeof CreateMasterTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-master-hotel': {
      id: '/create-master-hotel'
      path: '/create-master-hotel'
      fullPath: '/create-master-hotel'
      preLoaderRoute: typeof CreateMasterHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-invoice': {
      id: '/create-invoice'
      path: '/create-invoice'
      fullPath: '/create-invoice'
      preLoaderRoute: typeof CreateInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-booking': {
      id: '/create-booking'
      path: '/create-booking'
      fullPath: '/create-booking'
      preLoaderRoute: typeof CreateBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clear-auth-cache': {
      id: '/clear-auth-cache'
      path: '/clear-auth-cache'
      fullPath: '/clear-auth-cache'
      preLoaderRoute: typeof ClearAuthCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-edit': {
      id: '/booking-edit'
      path: '/booking-edit'
      fullPath: '/booking-edit'
      preLoaderRoute: typeof BookingEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-detail': {
      id: '/booking-detail'
      path: '/booking-detail'
      fullPath: '/booking-detail'
      preLoaderRoute: typeof BookingDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/vouchers/create': {
      id: '/vouchers/create'
      path: '/create'
      fullPath: '/vouchers/create'
      preLoaderRoute: typeof VouchersCreateRouteImport
      parentRoute: typeof VouchersRoute
    }
    '/transportation-booking-edit/$transportationBookingId': {
      id: '/transportation-booking-edit/$transportationBookingId'
      path: '/transportation-booking-edit/$transportationBookingId'
      fullPath: '/transportation-booking-edit/$transportationBookingId'
      preLoaderRoute: typeof TransportationBookingEditTransportationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportation-booking-detail/$transportationBookingId': {
      id: '/transportation-booking-detail/$transportationBookingId'
      path: '/transportation-booking-detail/$transportationBookingId'
      fullPath: '/transportation-booking-detail/$transportationBookingId'
      preLoaderRoute: typeof TransportationBookingDetailTransportationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-orders/create': {
      id: '/service-orders/create'
      path: '/create'
      fullPath: '/service-orders/create'
      preLoaderRoute: typeof ServiceOrdersCreateRouteImport
      parentRoute: typeof ServiceOrdersRoute
    }
    '/service-orders/$id': {
      id: '/service-orders/$id'
      path: '/$id'
      fullPath: '/service-orders/$id'
      preLoaderRoute: typeof ServiceOrdersIdRouteImport
      parentRoute: typeof ServiceOrdersRoute
    }
    '/service-order-edit/$serviceOrderId': {
      id: '/service-order-edit/$serviceOrderId'
      path: '/service-order-edit/$serviceOrderId'
      fullPath: '/service-order-edit/$serviceOrderId'
      preLoaderRoute: typeof ServiceOrderEditServiceOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-order-detail/$serviceOrderId': {
      id: '/service-order-detail/$serviceOrderId'
      path: '/service-order-detail/$serviceOrderId'
      fullPath: '/service-order-detail/$serviceOrderId'
      preLoaderRoute: typeof ServiceOrderDetailServiceOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-transport-edit/$routeId': {
      id: '/master-transport-edit/$routeId'
      path: '/master-transport-edit/$routeId'
      fullPath: '/master-transport-edit/$routeId'
      preLoaderRoute: typeof MasterTransportEditRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-transport-detail/$routeId': {
      id: '/master-transport-detail/$routeId'
      path: '/master-transport-detail/$routeId'
      fullPath: '/master-transport-detail/$routeId'
      preLoaderRoute: typeof MasterTransportDetailRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-hotel-edit/$hotelId': {
      id: '/master-hotel-edit/$hotelId'
      path: '/master-hotel-edit/$hotelId'
      fullPath: '/master-hotel-edit/$hotelId'
      preLoaderRoute: typeof MasterHotelEditHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-hotel-detail/$hotelId': {
      id: '/master-hotel-detail/$hotelId'
      path: '/master-hotel-detail/$hotelId'
      fullPath: '/master-hotel-detail/$hotelId'
      preLoaderRoute: typeof MasterHotelDetailHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user': {
      id: '/dashboard/user'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/create-transport-pricing/$routeId': {
      id: '/create-transport-pricing/$routeId'
      path: '/create-transport-pricing/$routeId'
      fullPath: '/create-transport-pricing/$routeId'
      preLoaderRoute: typeof CreateTransportPricingRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-hotel-pricing/$hotelId': {
      id: '/create-hotel-pricing/$hotelId'
      path: '/create-hotel-pricing/$hotelId'
      fullPath: '/create-hotel-pricing/$hotelId'
      preLoaderRoute: typeof CreateHotelPricingHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/create': {
      id: '/clients/create'
      path: '/create'
      fullPath: '/clients/create'
      preLoaderRoute: typeof ClientsCreateRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/client-detail/$clientId': {
      id: '/client-detail/$clientId'
      path: '/client-detail/$clientId'
      fullPath: '/client-detail/$clientId'
      preLoaderRoute: typeof ClientDetailClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-view/$bookingId': {
      id: '/booking-view/$bookingId'
      path: '/booking-view/$bookingId'
      fullPath: '/booking-view/$bookingId'
      preLoaderRoute: typeof BookingViewBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-transport-pricing/$routeId/$pricingId': {
      id: '/edit-transport-pricing/$routeId/$pricingId'
      path: '/edit-transport-pricing/$routeId/$pricingId'
      fullPath: '/edit-transport-pricing/$routeId/$pricingId'
      preLoaderRoute: typeof EditTransportPricingRouteIdPricingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-hotel-pricing/$hotelId/$pricingId': {
      id: '/edit-hotel-pricing/$hotelId/$pricingId'
      path: '/edit-hotel-pricing/$hotelId/$pricingId'
      fullPath: '/edit-hotel-pricing/$hotelId/$pricingId'
      preLoaderRoute: typeof EditHotelPricingHotelIdPricingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId/edit': {
      id: '/bookings/$bookingId/edit'
      path: '/$bookingId/edit'
      fullPath: '/bookings/$bookingId/edit'
      preLoaderRoute: typeof BookingsBookingIdEditRouteImport
      parentRoute: typeof BookingsRoute
    }
  }
}

interface BookingsRouteChildren {
  BookingsBookingIdEditRoute: typeof BookingsBookingIdEditRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsBookingIdEditRoute: BookingsBookingIdEditRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface ClientsRouteChildren {
  ClientsCreateRoute: typeof ClientsCreateRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsCreateRoute: ClientsCreateRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardUserRoute: typeof DashboardUserRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardUserRoute: DashboardUserRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ServiceOrdersRouteChildren {
  ServiceOrdersIdRoute: typeof ServiceOrdersIdRoute
  ServiceOrdersCreateRoute: typeof ServiceOrdersCreateRoute
}

const ServiceOrdersRouteChildren: ServiceOrdersRouteChildren = {
  ServiceOrdersIdRoute: ServiceOrdersIdRoute,
  ServiceOrdersCreateRoute: ServiceOrdersCreateRoute,
}

const ServiceOrdersRouteWithChildren = ServiceOrdersRoute._addFileChildren(
  ServiceOrdersRouteChildren,
)

interface VouchersRouteChildren {
  VouchersCreateRoute: typeof VouchersCreateRoute
}

const VouchersRouteChildren: VouchersRouteChildren = {
  VouchersCreateRoute: VouchersCreateRoute,
}

const VouchersRouteWithChildren = VouchersRoute._addFileChildren(
  VouchersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookingDetailRoute: BookingDetailRoute,
  BookingEditRoute: BookingEditRoute,
  BookingsRoute: BookingsRouteWithChildren,
  ClearAuthCacheRoute: ClearAuthCacheRoute,
  ClientsRoute: ClientsRouteWithChildren,
  CostsRoute: CostsRoute,
  CreateBookingRoute: CreateBookingRoute,
  CreateInvoiceRoute: CreateInvoiceRoute,
  CreateMasterHotelRoute: CreateMasterHotelRoute,
  CreateMasterTransportRoute: CreateMasterTransportRoute,
  CreateReceiptRoute: CreateReceiptRoute,
  CreateServiceOrderRoute: CreateServiceOrderRoute,
  CreateTransportationBookingRoute: CreateTransportationBookingRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvoiceDetailRoute: InvoiceDetailRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  MasterHotelsRoute: MasterHotelsRoute,
  MasterTransportRoute: MasterTransportRoute,
  ReceiptsRoute: ReceiptsRoute,
  RegisterRoute: RegisterRoute,
  ServiceOrdersRoute: ServiceOrdersRouteWithChildren,
  TransportationBookingsRoute: TransportationBookingsRoute,
  VouchersRoute: VouchersRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  BookingViewBookingIdRoute: BookingViewBookingIdRoute,
  ClientDetailClientIdRoute: ClientDetailClientIdRoute,
  CreateHotelPricingHotelIdRoute: CreateHotelPricingHotelIdRoute,
  CreateTransportPricingRouteIdRoute: CreateTransportPricingRouteIdRoute,
  MasterHotelDetailHotelIdRoute: MasterHotelDetailHotelIdRoute,
  MasterHotelEditHotelIdRoute: MasterHotelEditHotelIdRoute,
  MasterTransportDetailRouteIdRoute: MasterTransportDetailRouteIdRoute,
  MasterTransportEditRouteIdRoute: MasterTransportEditRouteIdRoute,
  ServiceOrderDetailServiceOrderIdRoute: ServiceOrderDetailServiceOrderIdRoute,
  ServiceOrderEditServiceOrderIdRoute: ServiceOrderEditServiceOrderIdRoute,
  TransportationBookingDetailTransportationBookingIdRoute:
    TransportationBookingDetailTransportationBookingIdRoute,
  TransportationBookingEditTransportationBookingIdRoute:
    TransportationBookingEditTransportationBookingIdRoute,
  EditHotelPricingHotelIdPricingIdRoute: EditHotelPricingHotelIdPricingIdRoute,
  EditTransportPricingRouteIdPricingIdRoute:
    EditTransportPricingRouteIdPricingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
